export const categories = [
  {
    id: '000',
    category: 'Nature',
    img: require('../assets/images/nature.jpg'),
    slug: 'nature',
  },
  {
    id: '111',
    category: 'Arts',
    img: require('../assets/images/Arts.jpg'),
    slug: 'arts',
  },
  {
    id: '222',
    category: 'Animals',
    img: require('../assets/images/animals.jpg'),
    slug: 'animals',
  },
  {
    id: '333',
    category: 'Experimental',
    img: require('../assets/images/experimental.jpg'),
    slug: 'experimental',
  },
  {
    id: '444',
    category: 'Fashion',
    img: require('../assets/images/fashion.jpg'),
    slug: 'fashion',
  },
  {
    id: '555',
    category: 'Food',
    img: require('../assets/images/food.jpg'),
    slug: 'food-drink',
  },
  {
    id: '666',
    category: 'People',
    img: require('../assets/images/peoples.jpg'),
    slug: 'people',
  },
  {
    id: '777',
    category: 'Sports',
    img: require('../assets/images/sports.jpg'),
    slug: 'atheletics',
  },
  {
    id: '888',
    category: 'Technology',
    img: require('../assets/images/tech.jpg'),
    slug: 'technology',
  },
  {
    id: '999',
    category: 'Patterns & Textures',
    img: require('../assets/images/textures.jpg'),
    slug: 'textures-patterns',
  },
  {
    id: '012',
    category: 'Travel',
    img: require('../assets/images/travel.jpg'),
    slug: 'travel',
  },
  {
    id: '345',
    category: 'Street',
    img: require('../assets/images/street.jpg'),
    slug: 'street-photography',
  },
  {
    id: '678',
    category: 'Interiors',
    img: require('../assets/images/interiors.jpg'),
    slug: 'interiors',
  },
  {
    id: '901',
    category: 'Random',
    img: require('../assets/images/random.jpg'),
    slug: 'random',
  },
];
